const test=require('node:test');
const assert=require('node:assert/strict');
const originalFetch=global.fetch;
const originalEnv={url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,anon:process.env.SUPABASE_ANON_KEY};
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test-service';process.env.SUPABASE_ANON_KEY='test-anon';
const releases=require('../lib/updates/index.cjs');
const installations=require('../lib/updates/installations.cjs');
const admin=require('../lib/updates/admin.cjs');
const worker=require('../lib/updates/worker.cjs');
function response(){return{code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.code=v;return this;},json(v){this.body=v;return this;},end(){return this;}};}
function json(value,status=200){return{ok:status<400,status,json:async()=>value};}
test('public update policy exposes only published metadata with no-store',async()=>{global.fetch=async url=>{assert.match(url,/status=eq.published/);return json([{id:'abc',build_number:13,minimum_build:12}]);};const res=response();await releases({method:'GET',headers:{},query:{platform:'android',build:11}},res);assert.equal(res.code,200);assert.equal(res.body.release.build_number,13);assert.match(res.headers['Cache-Control'],/no-store/);});
test('registration requires the authenticated owner and rejects untrusted web push hosts',async()=>{global.fetch=async url=>url.endsWith('/auth/v1/user')?json({id:'user-1'}):json([]);const res=response();await installations({method:'POST',headers:{authorization:'Bearer token'},body:{id:'12345678-1234-1234-1234-123456789abc',platform:'web',build_number:1,consent:true,push_endpoint:'https://127.0.0.1/secret',push_subscription:{endpoint:'https://127.0.0.1/secret',keys:{auth:'x',p256dh:'y'}}}},res);assert.equal(res.code,400);assert.match(res.body.error,/Proveedor web/);});
test('non-admin cannot create or publish releases',async()=>{global.fetch=async url=>url.endsWith('/auth/v1/user')?json({id:'user-1',app_metadata:{support_role:'agent'}}):json([]);const res=response();await admin({method:'POST',headers:{authorization:'Bearer token'},body:{action:'draft',platform:'android',build_number:13,version_label:'1.4.8'}},res);assert.equal(res.code,403);});
test('admin test send includes an already updated own device',async()=>{const queries=[];global.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return json({id:'user-1',app_metadata:{support_role:'admin'}});if(url.includes('/app_releases?'))return json([{id:'12345678-1234-1234-1234-123456789abc',platform:'android',build_number:14,status:'published'}]);if(url.includes('/update_installations?')){queries.push(url);return json([{id:'device-1'}]);}if(url.endsWith('/update_campaigns'))return json([{id:'campaign-1'}]);return json([]);};const res=response();await admin({method:'POST',headers:{authorization:'Bearer token'},body:{action:'send',test:true,release_id:'12345678-1234-1234-1234-123456789abc'}},res);assert.equal(res.code,200);assert.equal(res.body.eligible,1);assert.match(queries[0],/user_id=eq.user-1/);assert.doesNotMatch(queries[0],/build_number=lt/);});
test('worker rejects unauthenticated requests before accessing the queue',async()=>{const res=response();await worker({method:'GET',headers:{}},res);assert.equal(res.code,401);});
test('one installation cannot overwrite another user account',async()=>{global.fetch=async url=>url.endsWith('/auth/v1/user')?json({id:'user-2'}):url.includes('update_installations?')?json([{user_id:'user-1'}]):json([]);const res=response();await installations({method:'POST',headers:{authorization:'Bearer token'},body:{id:'12345678-1234-1234-1234-123456789abc',platform:'android',build_number:13,consent:false}},res);assert.equal(res.code,403);});
test.after(()=>{global.fetch=originalFetch;process.env.SUPABASE_URL=originalEnv.url;process.env.SUPABASE_SERVICE_ROLE_KEY=originalEnv.key;process.env.SUPABASE_ANON_KEY=originalEnv.anon;});
