const {admin,cors,db,error,queryEq,reply,rpc}=require('./_shared.cjs');
const rpcPublish=id=>rpc('publish_update_release',{p_release_id:id});
async function eligible(release,userId){const rows=[];for(let offset=0;;offset+=1000){const filter=userId?`&user_id=eq.${queryEq(userId)}`:`&build_number=lt.${release.build_number}`;const page=await db('update_installations',{query:`?platform=eq.${release.platform}&consent=eq.true&push_endpoint=not.is.null${filter}&select=id&order=id&limit=1000&offset=${offset}`});rows.push(...page);if(page.length<1000)break;}return rows;}
async function audit(actor,action,release,details={}){await db('update_audit',{method:'POST',body:{actor_id:actor.id,action,release_id:release||null,details}});}
module.exports=async(req,res)=>{if(cors(req,res))return;try{const actor=await admin(req);if(req.method==='GET'){const [releases,campaigns,auditRows,stats,observed]=await Promise.all([db('app_releases',{query:'?select=*&order=created_at.desc&limit=50'}),db('update_campaigns',{query:'?select=*&order=created_at.desc&limit=30'}),db('update_audit',{query:'?select=*&order=created_at.desc&limit=50'}),db('update_campaign_stats',{query:'?select=*'}),db('update_release_observed',{query:'?select=*'})]);const statsById=Object.fromEntries(stats.map(x=>[x.campaign_id,x]));const observedById=Object.fromEntries(observed.map(x=>[x.release_id,x.observed]));return res.json({releases:releases.map(x=>({...x,observed:observedById[x.id]||0})),campaigns:campaigns.map(x=>({...x,counts:statsById[x.id]})),audit:auditRows});}if(req.method!=='POST')return res.status(405).end();const body=req.body||{};const action=body.action;
if(action==='draft'){const platform=body.platform;if(!['android','web'].includes(platform))throw error('Plataforma inválida');const build=Number(body.build_number),minimum=Number(body.minimum_build||0);if(!Number.isSafeInteger(build)||build<1||!Number.isSafeInteger(minimum)||minimum<0||minimum>build)throw error('Números de versión inválidos');const label=String(body.version_label||'').trim(),notes=String(body.notes||'').trim();if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(label)||notes.length>2000)throw error('Texto inválido');const rows=await db('app_releases',{method:'POST',body:{platform,build_number:build,minimum_build:minimum,version_label:label,notes,status:'draft',created_by:actor.id}});await audit(actor,'draft',rows[0].id);return res.json({release:rows[0]});}
const id=String(body.release_id||'');if(!/^[0-9a-f-]{36}$/i.test(id))throw error('Versión inválida');const release=(await db('app_releases',{query:`?id=eq.${queryEq(id)}&limit=1`}))?.[0];if(!release)throw error('Versión inexistente',404);
if(action==='publish'){if(release.status!=='draft')throw error('Solo se publican borradores');if(release.platform==='android'){const redirect=await fetch('https://ruleto.mx/android/ruleto-drive.apk',{method:'HEAD',redirect:'manual'});const location=redirect.headers.get('location')||'';if(!location.includes(`/v${release.version_label}/`)||!location.includes(`Ruleto-Drive-${release.version_label}.apk`))throw error('El enlace público todavía no apunta a esta versión',409);const asset=await fetch(location,{method:'HEAD',redirect:'follow'});if(!asset.ok)throw error('La APK publicada no está disponible',409);}else{const response=await fetch('https://app.ruleto.mx/build-info.json',{cache:'no-store'});if(!response.ok||Number((await response.json()).build_number)!==release.build_number)throw error('La compilación web todavía no está desplegada',409);}const rows=await rpcPublish(id);await audit(actor,'publish',id);return res.json({release:rows[0]});}
if(action==='withdraw'){if(release.status!=='published')throw error('Esta versión no está publicada');await db('app_releases',{method:'PATCH',query:`?id=eq.${queryEq(id)}&status=eq.published`,body:{status:'withdrawn'}});await audit(actor,'withdraw',id);return res.json({ok:true});}
if(action==='minimum'){const minimum=Number(body.minimum_build);if(release.status!=='published'||!Number.isSafeInteger(minimum)||minimum<0||minimum>release.build_number)throw error('Mínimo inválido');await db('app_releases',{method:'PATCH',query:`?id=eq.${queryEq(id)}`,body:{minimum_build:minimum}});await audit(actor,'minimum',id,{minimum});return res.json({ok:true});}
if(action==='preview'){const installations=await eligible(release);return res.json({eligible:installations.length});}
if(action==='send'){if(release.status!=='published')throw error('Publica la versión antes de avisar');const kind=body.test===true?'test':'broadcast';const installations=await eligible(release,kind==='test'?actor.id:null);if(!installations.length)throw error(kind==='test'?'No hay dispositivos tuyos de esta plataforma con avisos activados':'No hay instalaciones elegibles para esta versión',409);if(kind==='broadcast'){const previous=await db('update_campaigns',{query:`?release_id=eq.${queryEq(id)}&kind=eq.broadcast&select=id&limit=1`});if(previous?.length)throw error('Ya se envió un aviso para esta versión',409);}const rows=await db('update_campaigns',{method:'POST',body:{release_id:id,kind,status:'queued',created_by:actor.id}});for(let offset=0;offset<installations.length;offset+=500)await db('update_deliveries',{method:'POST',body:installations.slice(offset,offset+500).map(x=>({campaign_id:rows[0].id,installation_id:x.id}))});await audit(actor,kind==='test'?'send_test':'send_broadcast',id,{count:installations.length});return res.json({campaign:rows[0],eligible:installations.length});}
if(action==='cancel'){const campaign=String(body.campaign_id||'');const current=(await db('update_campaigns',{query:`?id=eq.${queryEq(campaign)}&release_id=eq.${queryEq(id)}&select=id&limit=1`}))?.[0];if(!current)throw error('Campaña inexistente',404);await db('update_campaigns',{method:'PATCH',query:`?id=eq.${queryEq(campaign)}&status=in.(queued,sending)`,body:{status:'cancelled'}});await db('update_deliveries',{method:'PATCH',query:`?campaign_id=eq.${queryEq(campaign)}&status=eq.pending`,body:{status:'cancelled'}});await audit(actor,'cancel',id,{campaign});return res.json({ok:true});}
throw error('Acción inválida');}catch(e){reply(res,e);}};
