const webpush=require('web-push');
const {GoogleAuth}=require('google-auth-library');
const {cors,db,queryEq,reply,rpc}=require('./_shared.cjs');
const privateKey=process.env.WEB_PUSH_PRIVATE_KEY,publicKey=process.env.WEB_PUSH_PUBLIC_KEY;
let fcmClient;
async function sendFcm(endpoint,payload){const project=process.env.FIREBASE_PROJECT_ID;if(!project||!process.env.FIREBASE_SERVICE_ACCOUNT_JSON)throw Object.assign(new Error('Firebase no configurado'),{permanent:false});const credentials=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);const client=await (fcmClient||(fcmClient=new GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/firebase.messaging']}).getClient()));const token=await client.getAccessToken();const response=await fetch(`https://fcm.googleapis.com/v1/projects/${encodeURIComponent(project)}/messages:send`,{method:'POST',headers:{Authorization:`Bearer ${token.token}`,'Content-Type':'application/json'},body:JSON.stringify({message:{token:endpoint,notification:{title:'Nueva versión de Ruleto Drive',body:payload.body},data:{type:'update',release_id:payload.releaseId},android:{notification:{channel_id:'updates',tag:`update-${payload.releaseId}`}}}})});if(!response.ok){const e=new Error(`FCM ${response.status}`);e.statusCode=response.status;e.permanent=[400,404].includes(response.status);throw e;}return response.status;}
async function sendWeb(subscription,payload){if(!privateKey||!publicKey)throw new Error('Web Push no configurado');const host=new URL(subscription.endpoint).hostname;if(!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(host)&&!host.endsWith('.notify.windows.com'))throw Object.assign(new Error('Proveedor web no admitido'),{permanent:true});webpush.setVapidDetails('mailto:soporte@ruleto.mx',publicKey,privateKey);const result=await webpush.sendNotification(subscription,JSON.stringify({title:'Nueva versión de Ruleto Drive',body:payload.body,releaseId:payload.releaseId}),{TTL:86400,urgency:'normal',topic:`r${payload.releaseId.replace(/-/g,'').slice(0,30)}`});return result.statusCode;}
async function finish(id,status,attempts,providerStatus){const backoff=Math.min(60,Math.pow(2,attempts))*60000;await db('update_deliveries',{method:'PATCH',query:`?id=eq.${queryEq(id)}`,body:{status,next_attempt_at:new Date(Date.now()+backoff).toISOString(),locked_at:null,provider_status:providerStatus||null}});}
async function processBatch(){const claimed=await rpc('claim_update_deliveries',{p_limit:50});for(let offset=0;offset<(claimed||[]).length;offset+=10){await Promise.all(claimed.slice(offset,offset+10).map(async delivery=>{let status='pending',code=0;try{const [campaign,installation]=await Promise.all([db('update_campaigns',{query:`?id=eq.${delivery.campaign_id}&select=*&limit=1`}),db('update_installations',{query:`?id=eq.${delivery.installation_id}&select=*&limit=1`})]);const c=campaign?.[0],i=installation?.[0];const release=c&&(await db('app_releases',{query:`?id=eq.${c.release_id}&select=*&limit=1`}))?.[0];if(!c||!i||!release||c.status==='cancelled'||release.status!=='published'||!i.consent||!i.push_endpoint||i.build_number>=release.build_number){status='skipped';}else{const payload={body:release.notes?.slice(0,120)||`Actualiza a ${release.version_label}`,releaseId:release.id};code=i.platform==='android'?await sendFcm(i.push_endpoint,payload):await sendWeb(i.push_subscription,payload);status='accepted';}}catch(e){code=e.statusCode||e.status||0;status=e.permanent||[404,410].includes(code)||delivery.attempts>=3?'failed':'pending';if([404,410].includes(code))await db('update_installations',{method:'PATCH',query:`?id=eq.${delivery.installation_id}`,body:{consent:false,push_endpoint:null,push_subscription:null}}).catch(()=>{});console.error('Update delivery',delivery.id,e.message);}await finish(delivery.id,status,delivery.attempts,code);}));}const active=await db('update_campaigns',{query:'?status=in.(queued,sending)&select=id'});for(const campaign of active||[]){const pending=await db('update_deliveries',{query:`?campaign_id=eq.${campaign.id}&status=in.(pending,processing)&select=id&limit=1`});await db('update_campaigns',{method:'PATCH',query:`?id=eq.${campaign.id}`,body:pending?.length?{status:'sending'}:{status:'completed',completed_at:new Date().toISOString()}});}return {processed:claimed?.length||0};}
module.exports=async(req,res)=>{if(cors(req,res))return;if(!['POST','GET'].includes(req.method))return res.status(405).end();if(req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`||!process.env.CRON_SECRET)return res.status(401).end();try{res.json(await processBatch());}catch(e){reply(res,e);}};
module.exports.processBatch=processBatch;
