import { Capacitor } from '@capacitor/core';
import { Browser } from '@capacitor/browser';
import { PushNotifications } from '@capacitor/push-notifications';
import { apiUrl } from './apiClient';
import { supabase } from './supabaseClient';
import { pendingFor } from './offlineStore';
import { db } from './storage/db';

export const platform = Capacitor.isNativePlatform() ? 'android' : 'web';
export const buildNumber = Number(process.env.REACT_APP_BUILD_NUMBER || 0);
export const buildLabel = process.env.REACT_APP_BUILD_LABEL || 'local';
const KEY='ruleto-update-installation';
export const consentKey=userId=>`ruleto-update-consent-${userId}`;
let lastCheck=0;
let lastResult=(()=>{try{const saved=JSON.parse(localStorage.getItem(`ruleto-update-policy-${platform}`)||"null");const release=saved?.release;return saved?{release,required:Boolean(release&&buildNumber<Number(release.minimum_build)),available:Boolean(release&&buildNumber<Number(release.build_number))}:null;}catch{return null;}})();

export function installationId(userId){const key=`${KEY}-${userId}`;let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID();localStorage.setItem(key,id);}return id;}
async function token(){return (await supabase.auth.getSession()).data.session?.access_token;}
export async function authorized(path,options={}){const access=await token();if(!access)throw new Error('Inicia sesión para continuar');const response=await fetch(apiUrl(path),{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${access}`,...options.headers},cache:'no-store'});const data=response.status===204?{}:await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Servicio no disponible');return data;}
export async function checkUpdates(force=false){if(!force&&lastResult&&Date.now()-lastCheck<300000)return lastResult;lastCheck=Date.now();try{const response=await fetch(apiUrl(`/api/updates?platform=${platform}&build=${buildNumber}`),{cache:'no-store'});if(!response.ok)throw new Error('No se pudo comprobar la versión');const {release}=await response.json();lastResult={release,required:Boolean(release&&buildNumber<Number(release.minimum_build)),available:Boolean(release&&buildNumber<Number(release.build_number))};localStorage.setItem(`ruleto-update-policy-${platform}`,JSON.stringify(lastResult));return lastResult;}catch(e){if(lastResult)return lastResult;throw e;}}
async function registerInstallation(userId,consent=false,endpoint='',subscription=null){if(!userId)return;return authorized('/api/updates/installations',{method:'POST',body:JSON.stringify({id:installationId(userId),platform,build_number:buildNumber,consent,push_endpoint:endpoint,push_subscription:subscription})});}
export async function reportInstallation(userId){const enabled=localStorage.getItem(consentKey(userId))==='yes';if(!enabled)return registerInstallation(userId);if(platform==='android'){await registerAndroid(userId,false);}else{if(Notification.permission!=='granted'){localStorage.removeItem(consentKey(userId));return registerInstallation(userId);}const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub)await registerInstallation(userId,true,sub.endpoint,sub.toJSON());else{localStorage.removeItem(consentKey(userId));await registerInstallation(userId);}}}
function base64ToBytes(base64){const raw=atob(base64.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0));}
async function registerAndroid(userId,ask){let permissions=await PushNotifications.checkPermissions();if(permissions.receive==='prompt'&&ask)permissions=await PushNotifications.requestPermissions();if(permissions.receive!=='granted')return registerInstallation(userId);await PushNotifications.createChannel({id:'updates',name:'Actualizaciones',description:'Nuevas versiones de Ruleto Drive',importance:3});let resolveToken,rejectToken;const registered=new Promise((resolve,reject)=>{resolveToken=resolve;rejectToken=reject;});const listener=await PushNotifications.addListener('registration',value=>resolveToken(value.value));const failure=await PushNotifications.addListener('registrationError',value=>rejectToken(new Error(value.error||'No se recibió el token de Android')));let endpoint;try{await PushNotifications.register();endpoint=await Promise.race([registered,new Promise((_,reject)=>setTimeout(()=>reject(new Error('No se recibió el token de Android')),12000))]);}finally{await listener.remove();await failure.remove();}await registerInstallation(userId,true,endpoint);}
export async function enableUpdateNotifications(userId){if(platform==='android'){await registerAndroid(userId,true);}else{if(!('PushManager' in window)||!('Notification' in window))throw new Error('Este navegador no admite notificaciones');if(/iP(hone|ad|od)/.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches)throw new Error('En iPhone o iPad, primero añade Ruleto a la pantalla de inicio');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('No se concedió el permiso');const keyResponse=await fetch('/api/updates/vapid',{cache:'no-store'});const {publicKey}=await keyResponse.json();if(!publicKey)throw new Error('Notificaciones web aún no configuradas');const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64ToBytes(publicKey)});await registerInstallation(userId,true,sub.endpoint,sub.toJSON());}localStorage.setItem(consentKey(userId),'yes');}
export async function disableUpdateNotifications(userId){localStorage.removeItem(consentKey(userId));if(platform==='web'&&'serviceWorker' in navigator){const sub=await(await navigator.serviceWorker.ready).pushManager.getSubscription();await sub?.unsubscribe();}await registerInstallation(userId);}
export async function unlinkInstallation(userId){try{await authorized('/api/updates/installations',{method:'DELETE',body:JSON.stringify({id:installationId(userId)})});}catch(e){console.warn('No se pudo desvincular esta instalación',e);}localStorage.removeItem(`${KEY}-${userId}`);localStorage.removeItem(consentKey(userId));if(platform==='web'&&'serviceWorker' in navigator){const sub=await(await navigator.serviceWorker.ready).pushManager.getSubscription();await sub?.unsubscribe();}if(platform==='android')await PushNotifications.unregister().catch(()=>{});}
export function listenToUpdatePush(onUpdate){if(platform!=='android')return()=>{};let listeners=[];Promise.all([PushNotifications.addListener('pushNotificationActionPerformed',()=>onUpdate()),PushNotifications.addListener('pushNotificationReceived',()=>onUpdate())]).then(values=>listeners=values);return()=>listeners.forEach(x=>x.remove());}
export async function canReload(userId,activeDay){if(activeDay?.running)return 'Termina tu jornada antes de actualizar';if((await pendingFor(userId)).length)return 'Sincroniza los registros pendientes antes de actualizar';if((await db.outbox.where('user_id').equals(userId).count())>0)return 'Sincroniza los cambios pendientes antes de actualizar';return '';}
export async function updateNow(userId,activeDay){if(platform==='android'){await Browser.open({url:'https://ruleto.mx/descargar'});return;}const reason=await canReload(userId,activeDay);if(reason)throw new Error(reason);const registration=await navigator.serviceWorker.getRegistration('/');await registration?.update();if(registration?.waiting){const channel=new MessageChannel();const answer=new Promise((resolve,reject)=>{channel.port1.onmessage=e=>e.data.ok?resolve():reject(new Error(e.data.reason));setTimeout(()=>reject(new Error('No se pudo activar la actualización')),5000);});sessionStorage.setItem('ruleto-update-reload','yes');registration.waiting.postMessage({type:'ACTIVATE_UPDATE'},[channel.port2]);try{await answer;}catch(e){sessionStorage.removeItem('ruleto-update-reload');throw e;}return;}window.location.reload();}
export function setupWorkerReload(){if(platform!=='web'||!('serviceWorker' in navigator))return()=>{};const onChange=()=>{if(sessionStorage.getItem('ruleto-update-reload')==='yes'){sessionStorage.removeItem('ruleto-update-reload');window.location.reload();}};navigator.serviceWorker.addEventListener('controllerchange',onChange);return()=>navigator.serviceWorker.removeEventListener('controllerchange',onChange);}
export function postponed(releaseId){return Number(localStorage.getItem(`ruleto-update-postpone-${releaseId}`)||0)>Date.now();}
export function postpone(releaseId){localStorage.setItem(`ruleto-update-postpone-${releaseId}`,String(Date.now()+86400000));}
